CREATE TABLE IF NOT EXISTS descriptors (
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL COLLATE NOCASE
);

ALTER TABLE user_albums ADD COLUMN descriptors TEXT NOT NULL DEFAULT '[]';
